demo2/demo2/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include('polls.urls', namespace='polls'))
]

demo2/polls/urls.py
from django.conf.urls import url
from . import views

app_name = 'polls'

urlpatterns = [
    url(r'^index/$', views.Index, name='index'),
    url(r'^detail/(\d+)/$', views.Detail, name='detail'),
    url(r'^votehandler/$', views.VoteHandler, name='votehandler'),
    url(r'^result/(\d+)/$', views.Result, name='result'),
]

demo2/polls/models.py
from django.db import models

# Create your models here.

# 创建一个问题数据库
class QuestionInfo(models.Model):
    # 问题
    question = models.CharField(max_length=50)
    # 时间
    qpub_date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.question


# 创建一个投票详情统计数据库
class VoteInfo(models.Model):
    # 选项内容
    option = models.CharField(max_length=50)
    # 投票数
    vnum = models.IntegerField(default=0)
    # 外键 第一个参数为表名 第二个参数代表删除时的类型（CASCADEA 级联删除）
    vquestion = models.ForeignKey('QuestionInfo', on_delete=models.CASCADE)
    def __str__(self):
        return self.option

demo2/polls/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from .models import QuestionInfo, VoteInfo
# Create your views here.

def Index(request):
    # return HttpResponse('123')
    p1 = QuestionInfo.objects.all()
    # return render(request, 'polls/index.html', {'plist': "首页"})
    return render(request, 'polls/index.html', {'plist': p1})
def Detail(request,id):
    question = QuestionInfo.objects.get(pk=id)
    # return HttpResponse('123')
    return render(request, 'polls/detail.html', {'question': question})

def VoteHandler(request):

    choice = VoteInfo.objects.get(pk=request.POST['vote'])
    choice.vnum += 1
    choice.save()
    # return HttpResponse('123')
    return HttpResponseRedirect('/result/'+str(choice.id)+'/',)
def Result(request,oid):
    Vquestion = VoteInfo.objects.get(pk=oid).vquestion
    # return HttpResponse('123')
    return render(request,'polls/result.html', {"Vquestion":Vquestion})

demo2/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>详情页</title>
    <link rel="stylesheet" href="/static/css/main.css">

</head>
<body>
    <div class="con">
        <h2>问题描述：{{question}}</h2>
        <ul>
            <form action="{% url 'polls:votehandler' %}" method="post">
                {%for o in question.voteinfo_set.all %}
                    <li><input type="radio" name="vote" value="{{o.id}}">{{o.option}}</li>
                {% empty %}
                    <li>没有投票信息</li>
                {% endfor %}
                <br>
                <input type="submit" value="提交">
            </form>

        </ul>
    </div>

</body>
</html>

demo2/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>首页</title>
    {% load static from staticfiles %}
    <link rel="stylesheet" href="{% static '/css/main.css' %}">
</head>
<body>


    <div class="con">
        <h2>问题汇总</h2>

        {% for q in plist %}
            <ul>
                <li><a href="{% url 'polls:detail' q.id %}">{{q.question}}</a></li>
            </ul>
        {% endfor %}

    </div>

</body>
</html>

demo2/templates/polls/result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>投票结果</title>
    <link rel="stylesheet" href="/static/css/main.css">
</head>
<body>
    <div class="con">
         <h2>投票结果</h2>
        {{Vquestion.question}}
        <br>
        <ul>
            {% for o in Vquestion.voteinfo_set.all %}
            <li>{{o.option}}----{{o.vnum}}</li>
            {% empty %}
            <li>没有投票</li>

            {% endfor %}


        </ul>
    </div>

</body>
</html>