library/booktest/urls.py
from django.conf.urls import url
from . import views

app_name = 'booktest'

urlpatterns = [
    url(r'index/$', views.index, name='index'),
    url(r'edit/$', views.edit, name='edit'),
    url(r'sendemail/$', views.sendemail, name='sendemail'),
    url(r'readerlogin/$', views.readerlogin, name='readerlogin'),
    url(r'register/$', views.register, name='register'),
    url(r'^ajax/$', views.ajax,name='ajax'),
    url(r'^ajaxajax/$', views.ajaxajax,name='ajaxajax'),

    url(r'^login/$',views.login, name='login'),

    url(r'^verifycode/$', views.verifycode, name='ajax')

]

library/library/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include



urlpatterns = [
    path('admin/', admin.site.urls),
    url('^', include('booktest.urls', namespace='booktest'))
]

library/booktest/models.py
from django.db import models

"""建立数据库信息"""

# Create your models here.
"""用户信息"""
class UserInfo(models.Model):
    name = models.CharField(max_length=20)      #用户名
    password = models.CharField(max_length=20)  #密码
    school = models.CharField(max_length=20, null=True, blank=True)    #学院
    sno = models.CharField(max_length=20, null=True, blank=True)       #学号
    email = models.EmailField(max_length=20, null=True, blank=True)    #邮箱


"""图书信息"""
class BookInfo(models.Model):
    isbn = models.IntegerField()                    #ISBN
    name = models.CharField(max_length=20)          #书名
    author = models.CharField(max_length=20)        #作者
    publisher = models.CharField(max_length=20)     #出版商
    publishtime = models.DateTimeField( auto_now_add=True)            #出版时间


"""借阅信息"""
class BorrowInfo(models.Model):
    name = models.CharField(max_length=20)              #借阅者
    borrowtime = models.DateTimeField(auto_now=True)    #借阅日期
    returntime = models.DateTimeField(auto_now=True)    #归还日期
    username = models.ForeignKey('UserInfo', on_delete=models.CASCADE)       #用户外键
    bookname = models.ForeignKey('BookInfo', on_delete=models.CASCADE)       #图书外键

"""图片信息"""
class HotPic(models.Model):
    name = models.CharField(max_length=20)          #名字
    pic = models.ImageField(upload_to='hotpic')     #图片 存储的为图片的相对路径  upload_to 存储位置
    index = models.SmallIntegerField(unique=True)   #排序  unique=True 序号唯一，图片唯一


from tinymce.models import HTMLField

"""富文本"""
class MessageInfo(models.Model):
    title = models.CharField(max_length=20)     #添加富文本
    #富文本字段
    message = HTMLField()
    def __str__(self):
        return self.title

library/booktest/views.py
from django.shortcuts import render,redirect,reverse,HttpResponseRedirect,HttpResponse
from .models import UserInfo,BookInfo,BorrowInfo,HotPic,MessageInfo
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer,BadSignature,SignatureExpired

from django.core.mail import send_mail, send_mass_mail
from django.conf import settings
# Create your views here.

def index(request):
    """首页"""
    hotpics = HotPic.objects.all().order_by('index')
    messageinfos = MessageInfo.objects.all()
    return render(request, 'index.html', {'hotpics': hotpics, 'messageinfos': messageinfos})

"""
#1.得到序列化工具，构造序列化对象
# 生成秘钥，加密方式有效时间300秒
serutil = Serializer(settings.SECRET_KEY, 300)
# 加密字段为userid对应的值101
result = serutil.dumps({'userid':101}).decode('utf-8')
print(result)
send_mail("点击激活账户", " <a href = 'http://127.0.0.1:8000/booklibrary/active/%s'> 点击我激活账户</a> "%(resultid,),settings.DEFAULT_FROM_EMAIL,[email])

# 2.反序列化对象
deser = Serializer(settings.SECRT_KEY,300)
try:
    obj = deser.loads(idstr)
    user = UserInfo.objects.get(pk=obj['userid'])
    user.is_active = True
    user.save()
    return redirect(reverse('booklibrary:readerlogin'))

except SignatureExpired as e:
    return HttpResponse("连接失效")
"""


def edit(request):
    """注册"""
    if request.method == "GET":
        return render(request, 'edit.html')
    elif request.method == "POST":
        title = request.POST['title']
        message = request.POST['message']
        # 将接收的信息存进数据库
        messageinfo = MessageInfo(title=title, message=message)
        # 将接收的信息存进数据库
        # messageinfo = MessageInfo()
        # messageinfo.title = title
        # messageinfo.message = message
        messageinfo.save()
        return redirect(reverse('booktest:index'))

def sendemail(request):
    """发送文件"""
    try:
        from django.conf import settings
        send_mail("Django邮件0", "Django可以发送邮件", settings.DEFAULT_FROM_EMAIL, ["2430756697@qq.com", "2606662988@qq.com"])
        send_mass_mail((("Django邮件1", "Django可以发送邮件", settings.DEFAULT_FROM_EMAIL,
        ["2606662988@qq.com", "2606662988@qq.com"]),
        ("Django邮件2", "Django可以发送邮件", settings.DEFAULT_FROM_EMAIL,
        ["2606662988@qq.com", "2606662988@qq.com"])))
        print('发送成功')
        # return HttpResponse('发送成功')
    except Exception as e:
        print(e)
        return HttpResponseRedirect("发送失败")
    return HttpResponse("发送成功")

# def readerregister(request):
#     if request.method == "GET":
#         return render(request,)

def readerlogin(request):
    """登录"""
    return render(request, 'reader_login.html')
    # return HttpResponse('登录页面')

def register(request):
    """注册"""
    if request.method == 'GET':
        return render(request, 'register.html')
        # return HttpResponse('注册页面')

    elif request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        if password != request.POST['password2']:
            error = '密码输入不一致'
            return render(request, 'register.html', {'error': error})
        college = request.POST['college']
        number = request.POST['number']
        email = request.POST['email']
        userinfo = UserInfo(name=username, password=password, school=college, sno=number, email=email)
        userinfo.save()

        return render(request, 'reader_login.html')
        # return HttpResponse('用户注册信息提交数据库成功！')

def ajax(request):
    """ajax"""
    return render(request, 'ajax.html')

def ajaxajax(request):
    """ajaxajax"""
    if request.method == 'GET':
        return HttpResponse('ajaxajax GET请求成功')

    elif request.method == 'POST':
        return HttpResponse('ajaxajax POST请求成功')

library/templates/ajax.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Ajax</title>

    <script src="/static/js/lib/jquery/jquery-2.1.4.js"></script>

    <script>
        $(function(){

            $('#load').click(function(){
                console.log('标签加载完毕');
                //在页面按钮下显示data文件夹内的内容
                $('#info').load('/static/data/data.txt');
                $.ajax({
                    url:"/ajaxajax/",
                    type:'post',
                    data:{'csrfmiddlewaretoken': $('input[name=csrfmiddlewaretoken]').val()},
                    success:function (data) {
                        console.log(data);
                    }
                })
            })
        })
    </script>


</head>
<body>
    {% csrf_token %}
    <button id="load">点击load内容</button>
    <div id="info"></div>
    <div id="info2"></div>
</body>
</html>

library/templates/ajaxlogin.html
{% extends 'base.html' %}
{% block title %}登录{% endblock %}
    <script src="/static/js/lib/jquery/jquery-2.1.4.js"></script>
<script>
   $(function () {
       $('#username').blur(function () {
           $.ajax({
               url:'/booktest/checkuser/',
               type:'post',
               data:{
                   'csrfmiddlewaretoken':$('input[name=csrfmiddlewaretoken]').val(),
                   'username':$('#username').val()
               },
               success:function (data) {
                   $('#usernameinfo').text(data);
               }
           })
       })
    

   })

</script>



{% block body %}
<h2>登录</h2>

<form action="{% url ''booktest:ajaxlogin %}" method="post">
    {% csrf_token %}
    用户名： <input type="text" name="username"> <span id="usernameinfo"></span> <br>
    密码： <input type="password" name="password"> <br>
    <input type="submit" value="登录">
    
    
</form>

library/templates/index.html
{% extends "layout.html" %}
{% block title %}主页{% endblock %}
{% block link %}

  <a href="#">管理员登录 </a>|
  <a href=" {% url 'booktest:readerlogin' %} ">读者登录 </a>
{% endblock %}

{% block body %}
  <h2>欢迎使用</h2>
  <div class="hotpic">



    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
        <li data-target="#carousel-example-generic" data-slide-to="1"></li>
        <li data-target="#carousel-example-generic" data-slide-to="2"></li>
      </ol>

      <!-- Wrapper for slides -->

      <div class="carousel-inner" role="listbox">
        {% for pic in hotpics %}
          {% if pic.id == 1 %}
            <div class="item active">
              <img src="/static/media/{{pic.pic.url}}" alt="加载失败">
              <div class="carousel-caption">
                广告词/水印
              </div>
            </div>
          {% else %}
            <div class="item">
              <img src="/static/media/{{pic.pic.url}}" alt="加载失败">
              <div class="carousel-caption">
                广告词/水印
              </div>
            </div>
          {% endif %}
        {% empty %}
          没有图片
        {% endfor %}
      </div>

      <!-- Controls -->
      <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>



  </div><br>

    <div>
        <a href="/edit/">添加富文本</a><br>
        {% for message in messageinfos %}
        <br>
        标题：{{message.title}}<br>
        内容：{{message.message|safe}}
        {% empty %}
        没有文章信息
        {% endfor %}
    </div>


{% endblock %}

library/templates/manager.html
{% extends 'layout.html' %}
{% block title%} 功能导航 {% endblock %}
{% block link%} 
	<a href="{{ url_for('logout')}}"> 注销 [{{ g.user}}]</a> | 
	<a href="{{ url_for('manager_books') }}"> 图书管理 </a> |
	<a href="{{ url_for('manager_users') }}"> 用户管理 </a> 
{%  endblock%}

library/templates/manager_books_delete.html
{% extends "layout.html" %}
{% block title %} 删除书目 {% endblock %}
{% block link %}
	<a href="{{ url_for('manager_books')}}"> 返回 </a>
{% endblock %}

{% block body %}
	<h2> 删除书目 </h2>
	{% if error %}
	<div class=error>
	  <strong>Errror : </strong> {{error}}
	</div>
	{% endif %}  
	<form action="" method=post>
	  <dl>
	    <dt>请输入书目ISBN:</dt>
	    <dd><input type=text name=id size=30> </dd>	
    <div class=actions><input type=submit value="删除"></div>
  </form>
{% endblock %}

library/templates/manager_modify.html
{% extends "layout.html" %}
{% block title %} 修改书目信息 {% endblock %}
{% block link %} 
	{% if book %}
	<a href="{{ url_for('manager_book', id=book.book_id)}}"> 返回 </a>
	{% endif %}
{% endblock %}
{% block body %}
	<h2> 修改书目信息 </h2>
	{% if error %}
	<div class = error>
	  <strong>Error : </strong> {{error}}
	</div>
	{% endif %}
	{% if book %}
	<form action="" method=post>
	  <dl>
	    <dt>书名:</dt>
	    <dd><input type=text name=name size=30 value={{book.book_name}}> </dd>
	    <dt>作者:</dt>
	    <dd><input type=text name=author size=30 value={{book.author}}> </dd>
	    <dt>出版社:</dt>
	    <dd><input type=text name=company size=30 value={{book.publish_com}}> </dd>
	    <dt>出版日期:</dt>
	    <dd><input type=text name=date size=30 value={{book.publish_date}}> </dd>
	  </dl>
	  <div class=actions>
	    <input type=submit value="修改">
	  </div>
	</form>
	{% endif %}
{% endblock %} 

library/templates/manager_user_modify.html
{% extends "layout.html" %}
{% block title %} 用户信息修改 {% endblock %}
{% block link %} 
	<a href="{{ url_for('manager_user', id=user.user_id)}}"> 返回 </a>
{% endblock %}
{% block body %}
	{% if error %}
	<div class=error>
	  <strong>Errror : </strong> {{error}}
	</div>
	{% endif %}  
	<form action="" method=post>
	  <dl>
	    <dt>用户名:</dt>
	    <dd><input type=text name=username size=30 value={{user.user_name}}> </dd>	
	    <dt>请输入新密码(不输入就是不修改):</dt>
	    <dd><input type=password name=password size=30> </dd>
	    <dt>学院:</dt>
	    <dd><input type=text name=college size=30 value={{user.college}}> </dd>
	    <dt>学号:</dt>
	    <dd><input type=text name=number size=30 value={{user.num}}> </dd>
	    <dt>邮箱:</dt>
	    <dd><input type=text name=email size=30 value={{user.email}}> </dd>
	  </dl>
	  <div class=actions><input type=submit value="确定"></div>
	</form>

{% endblock %}

library/templates/manager_userinfo.html
{% extends "layout.html" %}
{% block title %} 用户主页 {% endblock %}

{% block link %}
	<a href="{{ url_for('manager_users') }}"> 返回  </a>  |
	<a href="{{ url_for('manger_user_modify', id=user.user_id)}}"> 修改 </a> | 
	<a href="{{ url_for('manger_user_delete', id=user.user_id)}}"> 注销 </a>
{% endblock %}
{% block body  %}
	<h2> 用户信息 </h2>
	{% if user %}
	<li> 用户名 {{user.user_name}} </li>
	<li> 学院名 {{user.college}} </li>
	<li> 学号 {{user.num}} </li>
	<li> 邮箱 {{user.email}} </li>
	{% endif %}

{% endblock %}

library/templates/manager_users.html
{% extends 'layout.html' %}
{% block title%} 用户管理 {% endblock %}
{% block link%} 
	<a href="{{ url_for('manager')}}"> 返回 </a> 
{%  endblock%}
{% block body%}
	<h2> 用户管理 </h2>
	<table width="600" border="1", align="center">
	  <tr>
	    <th align="center"> 用户名 </th>
	    <th align="center"> 用户信息 </th>
	  </tr>
	  {% for user in users%}
	  <tr>
	    <th align="center"> {{user.user_name}}</th>
	    <th align="center"> <a href="{{ url_for('manager_user', id=user.user_id)}}"> 点击进入 </a> </th>
	  </tr>
	  {% endfor %}
	</table>
{% endblock%}

library/templates/reader.html
{% extends 'layout.html' %}
{% block title %} 欢迎使用 {% endblock %}
{% block link %} 
	<a href="{{url_for('logout')}}"> 注销[{{g.user}}] </a> | 
	<a href="{{url_for('reader_query')}}"> 查询 </a> | 
	<a href="{{url_for('reader_info')}}"> 查看个人信息 </a> |
	<a href="{{url_for('reader_histroy')}}"> 查看阅读记录 </a>

{% endblock %}

{% block body %}
	<h2> 欢迎使用 </h2>
{% endblock %}

library/templates/reader_book.html
{% extends 'layout.html' %}

{% block title %} 书目信息 {% endblock %}
{% block link %} 
	{% if book %}
	<a href="{{ url_for('reader')}}"> 返回 </a>
	{% endif %}
{% endblock %}

{% block body %}
	{% if error %}
	<div class=error>
	  <strong>Errror : </strong> {{error}}
	</div>
	{% endif %}
	<h2> 书目信息 </h2>
	{% if book %}
	<li> ISBN            	{{book.book_id}} </li>
	<li> 书名        		{{book.book_name}} </li>
	<li> 作者        		{{book.author}} </li>	
	<li> 出版社     	{{book.publish_com}} </li>
	<li> 出版日期   	{{book.publish_date}} </li>
	{% endif %}
	<div >
	  <h2 > 借阅信息 </h2>
	  {% if reader  %}
	  <li> 借阅者姓名 {{reader.user_name}}</li>
	  <li> 借阅日期  {{reader.date_borrow}}</li>
	  <li> 还书日期  {{reader.date_return}}</li>
	  {% else %}
	  <li> 无 </li>
	  {% endif %}
	  <form action="" method=post>
	    <div class=actions>
	      <input type=submit value="借阅">
	    </div>
	  </form>

{% endblock %}

library/templates/reader_histroy.html
{% extends "layout.html" %}
{% block title %} 阅读记录 {% endblock %}
{% block link %} 
	<a href="{{ url_for('reader')}}"> 返回 </a>
{% endblock %}
{% block body %}
	<table width="600" border="1" align="center">
	  <tr>
	    <th align="center"> 书名 </th>
	    <th align="center"> 借书日期 </th>	
	    <th align="center"> 还书日期 </th>
	    <th align="center"> 状态 </th>
	  </tr>
	  {% for histroy in histroys %}
	  <tr>
	    <th align="center"> {{histroy.book_name}} </th>
	    <th align="center"> {{histroy.date_borrow}}</th>
	    <th align="center"> {{histroy.date_return}} </th> 
	    <th align="center"> {{histroy.status}} </th>
	  </tr>
	  {% endfor %}
	</table>	

{% endblock %}

library/templates/reader_modify.html
{% extends "layout.html" %}
{% block title %} 个人信息修改 {% endblock %}
{% block link %} 
	<a href="{{ url_for('reader')}}"> 返回 </a>
{% endblock %}
{% block body %}
	{% if error %}
	<div class=error>
	  <strong>Errror : </strong> {{error}}
	</div>
	{% endif %}  
	<form action="" method=post>
	  <dl>
	    <dt>用户名:</dt>
	    <dd><input type=text name=username size=30 value={{user.user_name}}> </dd>	
	    <dt>请输入新密码(不输入就是不修改):</dt>
	    <dd><input type=password name=password size=30> </dd>
	    <dt>学院:</dt>
	    <dd><input type=text name=college size=30 value={{user.college}}> </dd>
	    <dt>学号:</dt>
	    <dd><input type=text name=number size=30 value={{user.num}}> </dd>
	    <dt>邮箱:</dt>
	    <dd><input type=text name=email size=30 value={{user.email}}> </dd>
	  </dl>
	  <div class=actions><input type=submit value="确定"></div>
	</form>

{% endblock %}

library/templates/reader_query.html
{% extends "layout.html" %}
{% block title%} 查询  {% endblock %}
{% block link %} 
	<a href="{{ url_for('reader') }}"> 返回 </a>
{% endblock %}
{% block body %}
	<h2> 查询 </h2> 
	{% if error %}
	<div class=error>
	  <strong>Errror : </strong> {{error}}
	</div>
	{% endif %}  
    <div class=actions>
	  <form action="" method="post">
	    <dd>
	      <select name="item">
		<option value="name"> 书名 </option>
		<option value="author"> 作者 </option>
	      </select>
	      <input type="text" name="query" size="80"> 
	      <input type="submit" value="查询">
	    </dd> 
	  </form>
	</div>
	{% if books %}
	<table width="600" border="1" align="center">
	  <tr>
	    <th align="center"> ISBN </th>
	    <th align="center"> 书名 </th>
	    <th align="center"> 作者</th>
	    <th align="center"> 出版商 </th>
	    <th align="center"> 出版时间 </th>	
	    <th align="center"> 查看信息 </th>
	  </tr>
	  {% for book in books %}
	  <tr>
	    <th align="center"> {{book.book_id}}</th>
	    <th align="center"> {{book.book_name}} </th>
	    <th align="center"> {{book.author}}</th>
	    <th align="center"> {{book.publish_com}} </th>
	    <th align="center"> {{book.publish_date}}</th>
	    <th align="center"> <a href="{{ url_for('reader_book', id=book.book_id)}}"> 点击进入 </a> </th>
	  </tr>
	  {% endfor %}
	  {% endif %}
	</table>	
{% endblock %}