blog/blog/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from haystack.views import SearchView

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include('blogtest.urls', namespace='blogtest')),
    url(r'^', include('comment.urls', namespace='comment')),
    # 全文检索路由
    url('search/',SearchView(),name='haystack_search'),

]

blog/blogtest/urls.py
from django.conf.urls import url
from . import views
from .feed import PostFeed
app_name = 'blogtest'

urlpatterns = [
    # 首页
    url(r'blogtest/$', views.index, name='index'),
    # 详情页
    url(r'^detail/(\d+)/$', views.detail, name='detail'),
    # 博客
    url(r'fullwidth/$', views.fullwidth, name='fullwidth'),
    # 关于
    url(r'about/$', views.about, name='about'),
    # 联系
    url(r'contact/$', views.contact, name='contact'),
    # 搜索单独建立了文件夹
    # 归档
    url(r'archives/(\d+)/(\d+)/$', views.archives, name='archives'),
    # 分类
    url(r'category/(\d+)/$', views.category, name='category'),
    # 标签云
    url(r'tag/(\d+)/$', views.tag, name='tag'),
    # RSS
    url(r'^rss/$', PostFeed(), name='rss')

]

blog/comment/urls.py
from django.conf.urls import url
from . import views

app_name = 'comment'

urlpatterns = [
    # 接收评论信息
    url(r'^comitcoment/(\d+)/$', views.comitcoment, name='comitcoment'),


]

blog/blogtest/models.py
from django.db import models

# Create your models here.

# 分类表
class Category(models.Model):
    cname = models.CharField(max_length=20)
    def __str__(self):
        return self.cname
# 标签表
class Tag(models.Model):
    tname = models.CharField(max_length=20)
    def __str__(self):
        return self.tname
# 文章表
class Post(models.Model):
    ptitle = models.CharField(max_length=50)
    psummary = models.CharField(max_length=200)
    pbody = models.TextField(max_length=100000)
    creat_time = models.DateTimeField(auto_now_add=True)
    modified_time = models.DateTimeField(auto_now=True)
    category = models.ForeignKey('Category', on_delete=models.CASCADE)
    tags = models.ManyToManyField('Tag')
    author = models.CharField(max_length=20)
    read = models.PositiveIntegerField(default=0)
    def __str__(self):
        return self.ptitle

blog/comment/models.py
from django.db import models
from blogtest.models import Post

# Create your models here.

class Comment(models.Model):
    name = models.CharField(max_length=20)
    email = models.EmailField(blank=True, null=True)
    url = models.URLField(blank=True, null=True)
    comment = models.TextField()
    comment_time = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

blog/comment/forms.py
"""
自动生成表单

"""
from django.forms import ModelForm
from .models import Comment

class CommentForm(ModelForm):
    class Meta():
        model = Comment
        fields = ['name', 'email', 'url', 'comment']

blog/blogtest/views.py
from django.shortcuts import render,reverse,redirect
from django.http import HttpResponse
from .models import Post,Category,Tag
from comment.forms import CommentForm
from comment.models import Comment
# Create your views here.

def index(request):
    # return HttpResponse('首页')
    postlist = Post.objects.all()

    return render(request,'blogtest/index.html',{'postlist':postlist,'title':'django新闻'})

def detail(request, id):
    # 详情
    postnum = Post.objects.get(pk=id)
    form = CommentForm()

    # commentnum = Comment.objects.all()

    return render(request,'blogtest/single.html', {'postnum': postnum, 'form': form})

def fullwidth(request):
    # 博客
    return render(request,'blogtest/full-width.html')


def about(request):
    # 关于
    return render(request, 'blogtest/about.html')

def contact(request):
    # 联系
    return render(request, 'blogtest/contact.html')

def archives(request,year,month):
    # 归档
    postlist = Post.objects.all().filter(modified_time__year=year, modified_time__month=month)
    return render(request, 'blogtest/index.html', {'postlist': postlist})

def category(request,id):
    # 分类
    postlist = Category.objects.get(pk=id).post_set.all()
    return render(request, 'blogtest/index.html', {'postlist': postlist})

def tag(request,id):
    # 标签云
    postlist = Tag.objects.get(pk=id).post_set.all()
    return render(request, 'blogtest/index.html', {'postlist': postlist})

blog/comment/views.py
from django.shortcuts import render,get_object_or_404,redirect,reverse
from django.http import HttpResponse,HttpResponseRedirect
from .forms import CommentForm
from blogtest.models import Post

# Create your views here.



def comitcoment(request,id):
    """评论功能"""
    post = get_object_or_404(Post,pk=id)
    if request.method == "POST":
        comment = CommentForm(request.POST)
        if comment.is_valid():
            comment = comment.save(commit=False)
            comment.post = post
            comment.save()
            return redirect(reverse('blogtest:detail',args=(id,)))
    else:
        return HttpResponse('评论失败')

blog/templates/blogtest/about.html
<!DOCTYPE html>
<html>
	<head>
		<title>Black &amp; White</title>

		<!-- meta -->
		<meta charset="UTF-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1">

	    <!-- css -->
		<link rel="stylesheet" href="css/bootstrap.min.css">
		<link rel="stylesheet" href="css/ionicons.min.css">
		<link rel="stylesheet" href="css/pace.css">
	    <link rel="stylesheet" href="css/custom.css">

	    <!-- js -->
	    <script src="js/jquery-2.1.3.min.js"></script>
	    <script src="js/bootstrap.min.js"></script>
	    <script src="js/pace.min.js"></script>
	    <script src="js/modernizr.custom.js"></script>
	</head>

	<body id="page">
		<div class="container">	
			<header id="site-header">
				<div class="row">
					<div class="col-md-4 col-sm-5 col-xs-8">
						<div class="logo">
							<h1><a href="index.html"><b>Black</b> &amp; White</a></h1>
						</div>
					</div><!-- col-md-4 -->
					<div class="col-md-8 col-sm-7 col-xs-4">
						<nav class="main-nav" role="navigation">
							<div class="navbar-header">
  								<button type="button" id="trigger-overlay" class="navbar-toggle">
    								<span class="ion-navicon"></span>
  								</button>
							</div>

							<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  								<ul class="nav navbar-nav navbar-right">
    								<li class="cl-effect-11"><a href="index.html" data-hover="Home">Home</a></li>
    								<li class="cl-effect-11"><a href="full-width.html" data-hover="Blog">Blog</a></li>
    								<li class="cl-effect-11"><a href="about.html" data-hover="About">About</a></li>
    								<li class="cl-effect-11"><a href="contact.html" data-hover="Contact">Contact</a></li>
  								</ul>
							</div><!-- /.navbar-collapse -->
						</nav>
						<div id="header-search-box">
							<a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
							<div id="search-form" class="search-form">
								<form role="search" method="get" id="searchform" action="#">
									<input type="search" placeholder="Search" required>
									<button type="submit"><span class="ion-ios-search-strong"></span></button>
								</form>				
							</div>
						</div>
					</div><!-- col-md-8 -->
				</div>
			</header>
		</div>

		<div class="content-body">
			<div class="container">
				<div class="row">
					<main class="col-md-12">
						<h1 class="page-title">About Me</h1>
						<article class="post">
							<div class="entry-content clearfix">
								<figure class="img-responsive-center">
									<img class="img-responsive" src="img/me.jpg" alt="Developer Image">
								</figure>
								<p>Responsive web design offers us a way forward, finally allowing us to design for the ebb and flow of things. There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly.</p>
								<p>Responsive web design offers us a way forward, finally allowing us to design for the ebb and flow of things. There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly.</p>
								<div class="height-40px"></div>
								<h2 class="title text-center">Social</h2>
								<ul class="social">
									<li class="facebook"><a href="#"><span class="ion-social-facebook"></span></a></li>
									<li class="twitter"><a href="#"><span class="ion-social-twitter"></span></a></li>
									<li class="google-plus"><a href="#"><span class="ion-social-googleplus"></span></a></li>
									<li class="tumblr"><a href="#"><span class="ion-social-tumblr"></span></a></li>
								</ul>
							</div>
						</article>
					</main>
				</div>
			</div>
		</div>
		<footer id="site-footer">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<p class="copyright">&copy; 2014 ThemeWagon.com</p>
					</div>
				</div>
			</div>
		</footer>

		<!-- Mobile Menu -->
		<div class="overlay overlay-hugeinc">
			<button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
			<nav>
				<ul>
					<li><a href="index.html">Home</a></li>
					<li><a href="full-width.html">Blog</a></li>
					<li><a href="about.html">About</a></li>
					<li><a href="contact.html">Contact</a></li>
				</ul>
			</nav>
		</div>

		<script src="js/script.js"></script>
		
	</body>
</html>

blog/templates/blogtest/base.html
{% load extend_fun %}
<!DOCTYPE html>
<html>
<head>
    <title>Black &amp; White</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="/static/css/pace.css">
    <link rel="stylesheet" href="/static/css/custom.css">

    <!-- js -->
    <script src="/static/js/jquery-2.1.3.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <script src="/static/js/pace.min.js"></script>
    <script src="/static/js/modernizr.custom.js"></script>
</head>

<body>
<h2>{{title|mylower}}</h2>
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="index.html"><b>Black</b> &amp; White</a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="{% url 'blogtest:index' %}" data-hover="首页">首页</a></li>
                            <li class="cl-effect-11"><a href="{% url 'blogtest:fullwidth' %}" data-hover="博客">博客</a></li>
                            <li class="cl-effect-11"><a href="{% url 'blogtest:about' %}" data-hover="关于">关于</a></li>
                            <li class="cl-effect-11"><a href="{% url 'blogtest:contact' %}" data-hover="联系">联系</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->

                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="/search/">
                            <input type="search" placeholder="搜索" required name="q">
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
</div>
<div class="copyrights">Collect from <a href="http://www.cssmoban.com/">网页模板</a></div>
<div class="copyrights">Modified by <a href="http://zmrenwu.com/">追梦人物的博客</a></div>


<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">
                {% block left %}

                {% endblock %}
            </main>
            <aside class="col-md-4">
                <div class="widget widget-recent-posts">
                    {% block toc %}

                    {% endblock %}
                    <h3 class="widget-title">最新文章</h3>
                    <ul>
                        <li>
                            {% getlatestposet as latestposet %}
                            {% for post in latestposet %}
                            <a href="{% url 'blogtest:detail' post.id %} ">
                                >{{post.ptitle}}<br>
                            {% endfor %}
                            </a>

                        </li>
                    </ul>
                </div>

                <div class="widget widget-archives">
                    <h3 class="widget-title">归档</h3>
                    <ul>
                        {% getarchives as archives %}
                        {% for post in archives %}
                        <li>
                            <a href="{% url 'blogtest:archives' post.year post.month %}">{{post.year}}年{{post.month}}月</a>
                        </li>
                        {% empty %}
                        没有文章
                        {% endfor %}
                    </ul>
                </div>

                <div class="widget widget-category">
                    <h3 class="widget-title">分类</h3>
                    <ul>
                        {% getcategory as category %}
                        {% for cat in category %}
                            <li>
                                <a href="{% url 'blogtest:category' cat.id %}">{{cat.cname}} <span class="post-count">（#）</span></a>
                            </li>
                        {% empty %}
                            没有相关新闻
                        {% endfor %}

                    </ul>
                </div>

                <div class="widget widget-tag-cloud">
                    <h3 class="widget-title">标签云</h3>
                    <ul>
                        {% gettag as tag %}
                        {% for t in tag %}
                        <li>
                            <a href="{% url 'blogtest:tag' t.id %}">{{t.tname}}</a>
                        </li>
                        {% empty %}
                        该标签没有内容
                        {% endfor %}
                    </ul>
                </div>
                <div class="rss">
                    <a href="{% url 'blogtest:rss' %}"><span class="ion-social-rss-outline"></span> RSS 订阅</a>
                </div>

            </aside>
        </div>
    </div>
</div>

{% block bottom %}
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 2017 - 采集自<a href="http://www.cssmoban.com/"
                                                        target="_blank" title="模板之家">模板之家</a>
                    - 由<a href="http://zmrenwu.com/" title="网页模板" target="_blank">追梦人物的博客</a>修改
                </p>
            </div>
        </div>
    </div>
</footer>
{% endblock %}

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="index.html">首页</a></li>
            <li><a href="full-width.html">博客</a></li>
            <li><a href="about.html">关于</a></li>
            <li><a href="contact.html">联系</a></li>
        </ul>
    </nav>
</div>

<script src="/static/js/script.js"></script>

</body>
</html>

blog/templates/blogtest/contact.html
<!DOCTYPE html>
<html>
	<head>
		<title>Black &amp; White</title>

		<!-- meta -->
		<meta charset="UTF-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1">

	    <!-- css -->
		<link rel="stylesheet" href="css/bootstrap.min.css">
		<link rel="stylesheet" href="css/ionicons.min.css">
		<link rel="stylesheet" href="css/pace.css">
	    <link rel="stylesheet" href="css/custom.css">

	    <!-- js -->
	    <script src="js/jquery-2.1.3.min.js"></script>
	    <script src="js/bootstrap.min.js"></script>
	    <script src="js/pace.min.js"></script>
	    <script src="js/modernizr.custom.js"></script>
	</head>

	<body id="page">
		<div class="container">	
			<header id="site-header">
				<div class="row">
					<div class="col-md-4 col-sm-5 col-xs-8">
						<div class="logo">
							<h1><a href="index.html"><b>Black</b> &amp; White</a></h1>
						</div>
					</div><!-- col-md-4 -->
					<div class="col-md-8 col-sm-7 col-xs-4">
						<nav class="main-nav" role="navigation">
							<div class="navbar-header">
  								<button type="button" id="trigger-overlay" class="navbar-toggle">
    								<span class="ion-navicon"></span>
  								</button>
							</div>

							<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  								<ul class="nav navbar-nav navbar-right">
    								<li class="cl-effect-11"><a href="index.html" data-hover="Home">Home</a></li>
    								<li class="cl-effect-11"><a href="full-width.html" data-hover="Blog">Blog</a></li>
    								<li class="cl-effect-11"><a href="about.html" data-hover="About">About</a></li>
    								<li class="cl-effect-11"><a href="contact.html" data-hover="Contact">Contact</a></li>
  								</ul>
							</div><!-- /.navbar-collapse -->
						</nav>
						<div id="header-search-box">
							<a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
							<div id="search-form" class="search-form">
								<form role="search" method="get" id="searchform" action="#">
									<input type="search" placeholder="Search" required>
									<button type="submit"><span class="ion-ios-search-strong"></span></button>
								</form>				
							</div>
						</div>
					</div><!-- col-md-8 -->
				</div>
			</header>
		</div>

		<div class="content-body">
			<div class="container">
				<div class="row">
					<main class="col-md-12">
						<h1 class="page-title">Contact</h1>
						<article class="post">
							<div class="entry-content clearfix">
								<form action="#" method="post" class="contact-form">
									<div class="row">
										<div class="col-md-6 col-md-offset-3">
											<input type="text" name="name" placeholder="Name" required>
											<input type="email" name="email" placeholder="Email" required>
											<input type="text" name="subject" placeholder="Subject" required>
											<textarea name="message" rows="7" placeholder="Your Message" required></textarea>
											<button class="btn-send btn-5 btn-5b ion-ios-paperplane"><span>Drop Me a Line</span></button>
										</div>
									</div>	<!-- row -->
								</form>
							</div>
						</article>
					</main>
				</div>
			</div>
		</div>
		<footer id="site-footer">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<p class="copyright">&copy; 2014 ThemeWagon.com</p>
					</div>
				</div>
			</div>
		</footer>

		<!-- Mobile Menu -->
		<div class="overlay overlay-hugeinc">
			<button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
			<nav>
				<ul>
					<li><a href="index.html">Home</a></li>
					<li><a href="full-width.html">Blog</a></li>
					<li><a href="about.html">About</a></li>
					<li><a href="contact.html">Contact</a></li>
				</ul>
			</nav>
		</div>

		<script src="js/script.js"></script>
		
	</body>
</html>

blog/templates/blogtest/index.html
{% extends 'blogtest/base.html' %}

{# 注册extend_fun，使标签可以被引用 #}
{% load extend_fun %}

{% block left %}


    {% comment %}
    {% getlatestposet as latestposet %}
    {# 循环标签 #}
    {% for post in latestposet %}
        {{post.ptitle}}
    {% endfor %}
    {% endcomment %}
<article class="post post-1">
    {% for post in postlist %}
    <header class="entry-header">
        <h1 class="entry-title">
            <a href="{% url 'blogtest:detail' post.id  %}">{{post.ptitle}}</a>
        </h1>
        <div class="entry-meta">
            <span class="post-category"><a href="#">{{post.category}}</a></span>
            <span class="post-date"><a href="#"><time class="entry-date"
                                                      datetime="2012-11-09T23:15:57+00:00">{{post.creat_time}}</time></a></span>
            <span class="post-author"><a href="#">{{post.author}}</a></span>
            <span class="comments-link"><a href="#">{{post.comment_set.all.count}} 评论</a></span>
            <span class="views-count"><a href="#">{{post.read}} 阅读</a></span>
        </div>

    </header>
    <div class="entry-content clearfix">
        <p>{{post.psummary}}</p>
        <div class="read-more cl-effect-14">
            <a href="{% url 'blogtest:detail' post.id  %}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
        </div>
    </div>
    {% endfor %}
</article>

{% comment  %}
 <!-- 简单分页效果
<div class="pagination-simple">
    <a href="#">上一页</a>
    <span class="current">第 6 页 / 共 11 页</span>
    <a href="#">下一页</a>
</div>
-->
<div class="pagination">
    <ul>
        <li><a href="">1</a></li>
        <li><a href="">...</a></li>
        <li><a href="">4</a></li>
        <li><a href="">5</a></li>
        <li class="current"><a href="">6</a></li>
        <li><a href="">7</a></li>
        <li><a href="">8</a></li>
        <li><a href="">...</a></li>
        <li><a href="">11</a></li>
    </ul>
</div>
{% endcomment %}

{% endblock %}

blog/templates/blogtest/single.html
{% extends 'blogtest/base.html' %}
{# load+文件目录 才能使用过滤器或者标签 #}
{% load extend_fun %}
{% block left %}
<article class="post post-1">

    <header class="entry-header">
        <h1 class="entry-title">{{postnum.ptitle}}</h1>
        <div class="entry-meta">
            <span class="post-category"><a href="#">{{postnum.category}}</a></span>
            <span class="post-date"><a href="#"><time class="entry-date"
                                                      datetime="2012-11-09T23:15:57+00:00">{{postnum.creat_time}}</time></a></span>
            <span class="post-author"><a href="#">{{postnum.author}}</a></span>
            <span class="comments-link"><a href="#">{{postnum.comment_set.all.count}} 评论</a></span>
            <span class="views-count"><a href="#">{{postnum.read}} 阅读</a></span>
        </div>
    </header>

    <div class="entry-content clearfix">
       {{postnum.pbody}}
    </div>

</article>
<section class="comment-area" id="comment-area">
    <hr>
    <h3>发表评论</h3>
    <form action="{% url 'comment:comitcoment' postnum.id %}" method="post" class="comment-form">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-4">
                <label for="id_name">名字：</label>
                {# <input type="text" id="id_name" name="name" required> #}
                {{form.name}}
            </div>
            <div class="col-md-4">
                <label for="id_email">邮箱：</label>
                {# <input type="email" id="id_email" name="email" required> #}
                {{form.email}}
            </div>
            <div class="col-md-4">
                <label for="id_url">网址：</label>
                {# <input type="text" id="id_url" name="url"> #}
                {{form.url}}
            </div>
            <div class="col-md-12">
                <label for="id_comment">评论：</label>
                {# <textarea name="comment" id="id_comment" required></textarea> #}
                {{form.comment}}
                <button type="submit" class="comment-btn">发表</button>
            </div>
        </div>    <!-- row -->
    </form>
    <div class="comment-list-panel">
        {% get_comment_list postnum.id as commentlist %}
        <h3>评论列表，共 <span>{{postnum.comment_set.all.count}}</span> 条评论</h3>
        {% for comment in postnum.comment_set.all %}
        <ul class="comment-list list-unstyled">
            <li class="comment-item">
                <span class="nickname">{{comment.name}}</span>
                <time class="submit-date" datetime="2012-11-09T23:15:57+00:00">{{comment.comment_time}}</time>
                <div class="text">
                    {{comment.comment}}
                </div>
            </li>

        </ul>
        {% endfor %}
    </div>
</section>
{% endblock %}

{% block toc %}
<div class="widget widget-content">
    <h3 class="widget-title">文章目录</h3>
    <ul>
        <li>
            <a href="#">教程特点</a>
        </li>
        <li>
            <a href="#">谁适合这个教程</a>
        </li>
        <li>
            <a href="#">在线预览</a>
        </li>
        <li>
            <a href="#">资源列表</a>
        </li>
        <li>
            <a href="#">获取帮助</a>
        </li>
    </ul>
</div>
{% endblock %}

blog/templates/search/search.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>搜索结果</title>
</head>
<body>
    {% if query %}
        {% for post in page.object_list %}
            <li><a href="{% url 'blogtest:detail' post.object.id %}">{{post.object.ptitle}}</a></li>
        {% empty %}
            没有找到页面
        {% endfor %}
    {% endif %}
</body>
</html>