demo1/booktest/urls.py
from django.conf.urls import url
from .import views

# 去除硬编码'booktest'与demo1中的urls.py中的 url内的namespace对应
app_name = 'booktest'

urlpatterns = [
    # url('index/',views.index),
    # url('index/$',views.index),
    url(r'^$', views.index, name='index'),
    url(r'^list/$', views.list, name='list'),
    # (\d+) 详情页页码
    url(r'^detail/(\d+)/$', views.detail, name='detail'),
    url(r'delete/(\d+)/$', views.delete, name='delete'),
    url(r'addHero/(\d+)/$', views.addHero, name='addHero'),
    url(r'addherohandler/$', views.addherohandler, name='addherohandler'),
]

demo1/demo1/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from django.http import HttpResponse

urlpatterns = [
    # 进入后台用admin/
    path('admin/', admin.site.urls),
    # include 指明路径 urls所在位置
    url(r'^', include('booktest.urls',namespace="booktest"))
]
"""
项目的URL声明
通过 urlpatterns 列表中的内容将路由和视图绑定
"""


"""
去除硬编码
1.给应用添加app_name
2.在项目url配置文件中 在include中给应用添加命名空间
3.在应用配置文件中 给url配置名字
4.在html中解除硬编码   {%url'命名空间：url名字'  参数 %}

"""

demo1/booktest/models.py
from django.db import models

# Create your models here.

"""
一对一的关系
"""
class Account(models.Model):
    username = models.CharField(max_length=20)

class Contact(models.Model):
    phone = models.CharField(max_length=11)
    account = models.OneToOneField(Account, on_delete=models.CASCADE)


"""
多对多关系
"""
class Host(models.Model):
    hostname = models.CharField(max_length=20)
    port = models.IntegerField()

class Application(models.Model):
    name = models.CharField(max_length=20)
    h = models.ManyToManyField(to='Host')

"""
BookInfo和HeroInfo是一对多的关系（一本书对应多个英雄）
"""
# 一
class BookInfo(models.Model):
    btitle = models.CharField(max_length=20)
    bpub_data = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.btitle
# 多
class HeroInfo(models.Model):
    hname = models.CharField(max_length=20)
    hgender = models.BooleanField(default=False)
    hcontent = models.CharField(max_length=50)
    # 外键 第一个参数为表名 第二个参数代表删除时的类型（CASCADEA 级联删除）
    hbook = models.ForeignKey('BookInfo', on_delete=models.CASCADE)
    def __str__(self):
        return self.hname

    def skill(self):
        return self.hcontent
    skill.short_description = '绝招'

    def sex(self):
        return self.hgender
    sex.short_description = '性别'



"""
自关联
"""
class Area(models.Model):
    title = models.CharField(max_length=30)



"""
python manage.py shell 进入命令：不需要运行项目就可以操作数据库
导入类  from bookset.models import HeroInfo,BookInfo
查找所有行 表名.objects.all()
根据主键查找 表名.objects.get(pk = 1)
添加对象 **.save()
修改    **.save()
删除    **.delete()

一对多：一方存在主键 多方存在主键也存在外键（一方中的主键）

一方.heroinfo_set.all()

类名.objects.create(列名=值)  不需要save
"""

"""
list_display=[]
list_filter=[]
search_fields=[]
list_per_page=10
"""

demo1/booktest/views.py
from django.shortcuts import render,reverse,redirect
from django.http import HttpResponse, HttpResponseRedirect
from .admin import BookInfo, HeroInfo
from django.template import loader
# Create your views here.
# 定义视图函数
def index(request):
#     print("请求",request)
#     return HttpResponse("首页")
#     加载模板（html页面）
#     template = loader.get_template('booktest/index.html')
    # 构造上下文（username 与html页面内容联系 ）
    # context = {"username":'wlh'}
    # 渲染模板
    # result = template.render(context=context)
    # 返回模板
    # return HttpResponse(result)

    return render(request,'booktest/index.html',{"username": "wlh"})

def list(request):
    print("请求",request)
    # BookInfo.objects.all() 查询BookInfo内的所有信息
    b1 = BookInfo.objects.all()
    return render(request, 'booktest/list.html', context={'booklist':b1})

def detail(request,id):
    # try:
    #     book = BookInfo.objects.get(pk=id)
    #     return HttpResponse(book)
    #     # return HttpResponse("详情页"+str(id))
    # except:
    #     return HttpResponse("请输入正确id")

    book = BookInfo.objects.get(pk=id)
    # return render(request, 'booktest/detail.html', {'book': book})
    return render(request, 'booktest/detail.html', context={'book': book})
    # return HttpResponse("请输入正确id")

def delete(request,id):
    try:
        BookInfo.objects.get(pk=id).delete()
        b1 = BookInfo.objects.all()
        # 使用render没有刷新请求url
        # return render(request, 'booktest/list.html', {'booklist':b1})
        # 重定向     重新向服务器发起请求 刷新url

        # return HttpResponseRedirect('/list/', {"booklist": b1})
        # 视图中解除硬编码 用 reverse
        # return HttpResponseRedirect(reverse('booktest:list'))
        # redirect是HttpResponseRedirect的简写
        return redirect(reverse('booktest:list'))

    except:
        return HttpResponse("删除失败")

def addHero(request,bookid):
        return render(request, 'booktest/addHero.html', {'bookid': bookid})


# 添加英雄信息进数据库
def addherohandler(request):
    bookid = request.POST['bookid']
    hname = request.POST['heroname']
    hgender = request.POST['sex']
    hconnect = request.POST['herocontent']

    book = BookInfo.objects.get(pk=bookid)

    hero = HeroInfo()
    hero.hname = hname
    hero.hgender = True
    hero.hcontent = hconnect
    hero.hbook = book
    hero.save()

    return HttpResponseRedirect('/detail/'+str(bookid)+'/', {'book': book})
    # return HttpResponse('添加成功')



"""
视图函数
将函数和路由绑定
"""


"""
html页面就是模板
创建模板文件夹 templates
配置模板目录  在os.path.join(BASE_DIR,'templates')
创建项目模板目录，创建模板

加载模板 temp=loader.get_template()
使用变量渲染模板 result = temp.render({})
返回  HttpResponse(result)
"""

demo1/templates/booktest/addHero.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>添加英雄</title>
    {% load static from staticfiles %}
    {#<link rel="stylesheet" href="/static/css/main.css">#}
    {#解除硬编码#}
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body>
    <div class="container">
        <h2>添加英雄</h2>
        <form action="{% url 'booktest:addherohandler' %} "method="post">
            英雄名：<input type="text" name="heroname">
            <br>
            性别：男<input type="radio" value="1" name="sex" checked>
                女<input type="radio" value="0" name="sex">
            <br>
            技能：<input type="text" name="herocontent">
            <br>
            <input type="hidden" value="{{bookid}}" name="bookid">
            <br>
            <input type="submit" value="添加">

        </form>

        <br>
        <br>



    </div>


</body>
</html>

demo1/templates/booktest/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>详情页</title>
    {% load static from staticfiles %}
    {#<link rel="stylesheet" href="/static/css/main.css">#}
    {#解除硬编码#}
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body>
    <div class="container">
        <h2>详情页</h2>
        <ul>
           {% for hero in book.heroinfo_set.all %}
                <li>{{hero.hname}} ------ {{hero.hcontent}}</li>
           {% empty %}
                <h3>没有角色信息</h3>
           {% endfor %}


        </ul>

        {#<a href="/booktest/list/">返回列表页</a>#}
        {#解除硬编码#}
        <a href="{% url 'booktest:list' %}">返回列表页</a>
        {#<a href="{% url 'booktest:addherohandler' %}">添加角色</a>#}
    </div>
</body>
</html>

demo1/templates/booktest/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>首页</title>
    <link rel="stylesheet" href="/static/css/main.css">
</head>
<body>
    <div class="container">
        {% if username %}
            <h2>书籍首页</h2>
            <h2>{{username}}</h2>
        {% else %}
            <h2>没有登录</h2>
        {% endif %}
        <br>
        <img src="/static/img/123.jpg" alt="图片加载失败">

        {#超级链接硬编码#}
        {#<a href="/booktest/list/">进入列表页</a>#}

        {#去除硬编码#}
        <a href="{% url 'booktest:list' %}">进入列表页</a>
    </div>


</body>
</html>

demo1/templates/booktest/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>列表页</title>
    <link rel="stylesheet" href="/static/css/main.css">
</head>
<body>
    <div class="container">
        <h1>书籍信息</h1>
        <ul>
            {% for book in booklist %}
                {#<li><a href="/booktest/list/{{book.id}}/">{{book.btitle}}</a></li>#}

            {# 去除硬编码 #}
                <li><a href="{% url 'booktest:detail' book.id %}">{{book.btitle}}</a>----
                    <a href="{% url 'booktest:delete' book.id %}">删除</a>----
                    <a href="{% url 'booktest:addHero' book.id %}">添加英雄</a>

                </li>
            {% empty %}
                <h3>没有信息</h3>
            {% endfor %}
        </ul>

        <!--<a href="/booktest/">返回</a>-->
        <a href="{% url 'booktest:index' %}">返回</a>
    </div>

</body>
</html>